# -*- coding: utf-8 -*-
"""Amazon Prime Project- Lakshita

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kwS6aomLoY80bQL-poPsnEyJdOk6zqoY
"""

import pandas as pd
import numpy as np

# Practice dataset — same structure as real Amazon Prime dataset
data = {
    'show_id': ['s1','s2','s3','s4','s5','s6','s7','s8','s9','s10',
                's11','s12','s13','s14','s15','s16','s17','s18','s19','s20',
                's21','s22','s23','s24','s25'],
    'type': ['Movie','TV Show','Movie','Movie','TV Show','Movie','Movie',
             'TV Show','Movie','Movie','TV Show','Movie','Movie','TV Show',
             'Movie','TV Show','Movie','TV Show','Movie','Movie',
             'TV Show','Movie','Movie','TV Show','Movie'],
    'title': ['The Shawshank Redemption','Friends','Inception','Forrest Gump',
              'Breaking Bad','The Dark Knight','Interstellar','The Office',
              'Gladiator','Joker','Stranger Things','Parasite','Dangal',
              'Mirzapur','The Matrix','Money Heist','3 Idiots','Dark',
              'Pulp Fiction','Gully Boy','Panchayat','The Godfather',
              'Wednesday','Squid Game','The Truman Show'],
    'director': ['Frank Darabont',np.nan,'Christopher Nolan','Robert Zemeckis',
                 np.nan,'Christopher Nolan','Christopher Nolan',np.nan,
                 'Ridley Scott','Todd Phillips',np.nan,'Bong Joon Ho',
                 'Nitesh Tiwari',np.nan,'Lana Wachowski',np.nan,
                 'Rajkumar Hirani',np.nan,'Quentin Tarantino','Zoya Akhtar',
                 np.nan,'Francis Ford Coppola',np.nan,np.nan,'Peter Weir'],
    'country': ['USA','USA','USA','USA','USA','USA','USA','USA','USA','USA',
                'USA','South Korea','India','India','USA','Spain','India',
                'Germany','USA','India','India','USA','USA','South Korea','USA'],
    'release_year': [1994,1994,2010,1994,2008,2008,2014,2005,2000,2019,
                     2016,2019,2016,2018,1999,2017,2009,2017,1994,2019,
                     2020,1972,2022,2021,1998],
    'rating': ['R','TV-14','PG-13','PG-13','TV-MA','PG-13','PG-13','TV-14',
               'R','R','TV-14','R','PG-13','A','R','TV-MA','PG-13','TV-MA',
               'R','A','TV-14','R','TV-14','TV-MA','PG-13'],
    'duration': ['142 min','10 Seasons','148 min','142 min','5 Seasons',
                 '152 min','169 min','9 Seasons','155 min','122 min',
                 '3 Seasons','132 min','161 min','3 Seasons','136 min',
                 '4 Seasons','170 min','3 Seasons','154 min','153 min',
                 '9 min','175 min','1 Season','1 Season','103 min'],
    'listed_in': ['Drama','Comedy','Sci-Fi','Drama','Crime','Action','Sci-Fi',
                  'Comedy','Action','Drama','Sci-Fi','Thriller','Drama',
                  'Crime','Sci-Fi','Thriller','Comedy','Mystery','Crime',
                  'Drama','Comedy','Crime','Fantasy','Thriller','Drama'],
    'description': ['Two prisoners bond over years','Six friends in NYC',
                    'Dream within dreams','Life is a box of chocolates',
                    'Chemistry teacher turns kingpin','Batman vs Joker',
                    'Journey through space','Office workplace comedy',
                    'Roman general betrayed','Gotham clown origin',
                    'Kids face supernatural','Class satire thriller',
                    'Wrestler daughters','Gangs of Mirzapur',
                    'Reality is a simulation','Money heist in Madrid',
                    'Engineering college life','Time travel mystery',
                    'Hitman literature','Rapper from Dharavi',
                    'Village panchayat life','Mafia family saga',
                    'Wednesday at Nevermore','Deadly survival game',
                    'Life is a TV show']
}

df = pd.DataFrame(data)

# Intentionally added a duplicate + missing values for cleanup practice
df = pd.concat([df, df.iloc[[2]]], ignore_index=True)   # duplicate row
df.loc[5, 'country'] = np.nan                            # missing country

# 💾 Save as a CSV file with your name!
df.to_csv('amazon_prime_sample_lakshita.csv', index=False)

df.head()

# ============ DATA UNDERSTANDING ============
print("SHAPE (rows, columns):", df.shape)
print("\nINFO:")
print(df.info())
print("\nMISSING VALUES per column:")
print(df.isnull().sum())

# ============ DATA CLEANUP ============
df = df.drop_duplicates()                        # 👯 removes duplicate Inception
df['country'] = df['country'].fillna('Unknown')  # 🕳️ fills missing country

print("\n✅ CLEANUP DONE!")
print("Shape after cleanup:", df.shape)          # one row less now!
print("\nMissing values after cleanup:")
print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,4))
sns.countplot(x='type', data=df, palette='pastel')
plt.title('Movies vs TV Shows on Amazon Prime')
plt.show()

"""**Remark (Chart 1):** Movies outnumber TV Shows on Amazon Prime.
**Insight:** The platform's strategy is movie-heavy.
"""

plt.figure(figsize=(10,4))
plt.hist(df['release_year'], bins=10, color='skyblue', edgecolor='black')
plt.title('Content by Release Year')
plt.show()

"""**Remark (Chart 2):** Most content was released after 2010.
**Insight:** Amazon expanded its library rapidly in the streaming era.
"""

plt.figure(figsize=(8,4))
df['listed_in'].value_counts().plot(kind='barh', color='salmon')
plt.title('Top Genres on Amazon Prime')
plt.show()

"""**Remark (Chart 3):** Drama and Comedy are the most common genres.
**Insight:** These genres attract the widest audience.
"""

plt.figure(figsize=(8,4))
df['rating'].value_counts().plot(kind='bar', color='mediumseagreen')
plt.title('Age Ratings Distribution')
plt.show()

"""**Remark (Chart 4):** R and PG-13 ratings dominate the platform.
**Insight:** Content mainly targets teen and adult viewers.
"""

plt.figure(figsize=(8,4))
df['country'].value_counts().head(10).plot(kind='bar', color='plum')
plt.title('Top Countries Producing Content')
plt.show()

"""**Remark (Chart 5):** USA produces the most content, India is second.
**Insight:** India is a key growth market for Amazon Prime.

"""

plt.figure(figsize=(8,4))
df['rating'].value_counts().plot(kind='bar', color='mediumseagreen')
plt.title('Age Ratings Distribution')
plt.show()

"""**Remark (Chart 4):** R and PG-13 ratings dominate the platform.
**Insight:** Content mainly targets teen and adult viewers.
"""

plt.figure(figsize=(8,4))
df['rating'].value_counts().plot(kind='bar', color='mediumseagreen')
plt.title('Age Ratings Distribution')
plt.show()

"""**Remark (Chart 4):** R and PG-13 ratings dominate the platform.
**Insight:** Content mainly targets teen and adult viewers.
"""

plt.figure(figsize=(8,4))
df['rating'].value_counts().plot(kind='bar', color='mediumseagreen')
plt.title('Age Ratings Distribution')
plt.show()

"""**Remark (Chart 4):** R and PG-13 ratings dominate the platform.
**Insight:** Content mainly targets teen and adult viewers.

## 💡 Hypotheses & Assumptions (made before analysis)

H1: Movies outnumber TV Shows on Amazon Prime. ✅ Proven by Chart 1.
H2: Most content was released after 2010. ✅ Proven by Chart 2.
H3: Drama and Comedy are the most common genres. ✅ Proven by Chart 3.
H4: Content mainly targets teen and adult audiences. ✅ Proven by Chart 4.
H5: USA and India produce most of the content. ✅ Proven by Chart 5.

## 🎯 Conclusion

From this EDA project on Amazon Prime TV Shows and Movies, I (Lakshita)
conclude the following:

1. Amazon Prime's catalog is movie-dominant, with TV shows forming a
   smaller share — an opportunity exists to expand series content.
2. Most content was released after 2010, showing rapid library growth
   during the streaming era.
3. Drama and Comedy are the leading genres, attracting the widest audience.
4. Content is skewed toward teen/adult ratings (R, PG-13), indicating a
   gap in family-friendly content.
5. USA leads content production, with India as the second-largest
   contributor — highlighting India as a key growth market.

### 📌 Business Recommendations:
- Invest in more TV series to capture binge-watching audiences.
- Produce more family-friendly content to fill the rating gap.
- Continue expanding Indian content to grow the international market.
"""

print("Total Titles:", len(df))
print("Movies:", (df['type']=='Movie').sum())
print("TV Shows:", (df['type']=='TV Show').sum())
print("Average Release Year:", round(df['release_year'].mean()))
print("Oldest Content:", df['release_year'].min())
print("Newest Content:", df['release_year'].max())
print("Most Common Rating:", df['rating'].mode()[0])
print("Top Country:", df['country'].mode()[0])
print("Top Genre:", df['listed_in'].mode()[0])

"""**Statistical Summary:** These numbers confirm our visual findings —
movie-heavy catalog, recent content growth, and adult-oriented ratings.
"""